### ISSUE TITLE
-host

### ISSUE THREAD

**Issue by robocop-bob** [adejoux/nmon2influxdb#1]
Hi 

I copied compiled version of  nmon2influx  from https://www.dropbox.com/s/zylemeaas1w2o2g/nmon2influx

When I try put docker IP :
../nmon2influx -host="192.168.59.104:8086" -file="nmonfile.nmon"  

I have error: 

```
flag provided but not defined: -host
Usage of ../nmon2influx:
  -admin="admin": influxdb administor user
  -file="nmonfile": nmon file
  -pass="password": influxdb administor password
```

When I try default 
../nmon2influx  -file="nmonfile.nmon" 
I have error: 

```
panic: runtime error: slice bounds out of range
goroutine 16 [running]:
runtime.panic(0x6c93a0, 0x8974ef)
    /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.main()
    /home/adejoux/devel/go/src/github.com/adejoux/nmon2influx/nmon2influx.go:254 +0xa03
goroutine 19 [finalizer wait]:
runtime.park(0x4164d0, 0x89b548, 0x899789)
    /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x89b548, 0x899789)
    /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
```

can you check if  compiled nmon2influx use -host ?

Best regards
robert

**Comment by adejoux** [comment]
Hello,

You was right. The binary version was too old. 

I updated it. It's the same link :
https://www.dropbox.com/s/zylemeaas1w2o2g/nmon2influx

I also fixed a bug where the database creation was done on localhost anyway.

Thanks

**Comment by ghost** [comment]
Thx , quick response... but issue still exist.

nmon_reports3 starting ok 

```
docker run -d -p 80:80 -p 8083:8083 -p 8086:8086 --name="nmon_reports3" -t adejoux/influxdb_grafana
bash-3.2$  boot2docker ip
192.168.59.104
```

Influxdb available at http://192.168.59.104:8083 - working , No possibile login admin/admin !

To run nmon2influx I create new docker cointainer with /bin/bash ( I am working on Mac , so I can't compile source).

```
docker run -t -i -d -P -v $HOME:/mnt debian:latest /bin/bash
root@5df5ae6aa948:/mnt# ping 192.168.59.104
PING 192.168.59.104 (192.168.59.104) 56(84) bytes of data.
```

Program nmon2influx still crash

```
./nmon2influx   -file="./nmonfile.nmon"
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x70d620, 0x9146cf)
    /usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.main()
    */home/adejoux/devel/go/src/github.com/adejoux/nmon2influx/nmon2influx.go:345 +0xbdf*

goroutine 19 [finalizer wait]:
runtime.park(0x4172d0, 0x918728, 0x916969)
    /usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x918728, 0x916969)
    /usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib/golang/src/pkg/runtime/proc.c:1445
```

Can you help?

Bestr regards 
Robert

**Comment by adejoux** [comment]
Hello,

I forgot to specify it but the admin user is created during the first run of nmon2influx :

./nmon2influx -file=/home/adejoux/logs/Cofares/zeus2_141203_1300.nmon
No administrator defined. **Creating user admin with password admin**
Creating database : nmon_reports
Creating database : grafana

Did you see the lines above during your first run ?

For information, you can connect with root/root on influxdb.

I see what happens in the error but not why it's happening. 
The error occurs when it try to split the nmon file line using the comma separator. I will put 

Can you send me your nmon file by email ? I would like to try to import it. 
Else i will generate a new version with a better error handling later today and send you the link.

Thanks again for the time spent on it :)

**Comment by ghost** [comment]
Hi,

All my runs fails with errors as above... 
user: root/root - working OK.

_I had to delete attached file_

You had perfect idea, I want check it , how it works :)

Did you try run nmon2influx from clean enviroment as I do?

```
run -t -i -d -P -v $HOME:/mnt debian:latest /bin/bash
./nmon2influx   -file="./nmonfile.nmon"
```

Best regards
robert

**Comment by adejoux** [comment]
Thanks.

I reproduced the error with your nmon file. 
I will fix it.

**Comment by adejoux** [comment]
I uploaded a new version skipping TOP lines for now. I am not sure how to manage them in influxdb. 

I hope it will work now. I can import your nmon file on my system :

![image](https://cloud.githubusercontent.com/assets/741174/7050426/97070396-de21-11e4-9dc6-b4ed95552cf8.png)

Thanks again

**Comment by ghost** [comment]
Hi,

it looks much better !

```
root@5df5ae6aa948:/mnt/# ./nmon2influx-4  -host="192.168.59.104:8086" file=./nmon/nmonfile.nmon
No administrator defined. Creating user admin with password admin
Creating database : nmon_reports
Creating database : grafana
no such file or directory: tmplfile
ERROR: unable to parse grafana template. Using default template.
Writing GRAFANA dashboard: hdzap_dashboard
```

When I open: http://192.168.59.104/grafana my Web looks like below :(
![screen shot 2015-04-08 at 8 23 07 pm](https://cloud.githubusercontent.com/assets/3903647/7052154/1e07f8a4-de2d-11e4-9453-c0aa4ef6363e.png)

**Comment by adejoux** [comment]
Yes. It's what is exected here. 

You need to import the dashboard generated by the tool. Here it's : hdzap_dashboard

After that, you click on the folder icon on the top right and select your file for import :
![image](https://cloud.githubusercontent.com/assets/741174/7052343/56f8fbd0-de2e-11e4-8ef7-7e64fbd431ca.png)

**Comment by ghost** [comment]
Yes, 

After import much better again....
Maybe Grafana is too slow ...  but it is probably my local env issue....
( now loading dashboard >20 minutes... and still waitng)...

Best regards
Robert

**Comment by ghost** [comment]
After 1h  ... waiting for Grafana refresh I have to give up... up to tommorow

**Comment by adejoux** [comment]
Can you send me the dashboard file you used? Normally grafana is really quick. For example, the nmon file you gave me  was was generated immediately. Try with it too if you can.

**Comment by ghost** [comment]
After few hours , still waiting:) 

Best regards

Robert

**Comment by adejoux** [comment]
grafana chart are almost immediate so something is wrong :) If you cannot send me the dashboard file can you put a screenshot to allow me to see where yo uare waiting ? 

thanks :)

**Comment by ghost** [comment]
Chrome Version 41.0.2272.118 (64-bit)
![screen shot 2015-04-10 at 8 57 07 am](https://cloud.githubusercontent.com/assets/3903647/7089209/7d43b1aa-df9a-11e4-899d-b0b62294f813.png)

Dashboard sent to your email.

best regards
robert

**Comment by adejoux** [comment]
Hello,

i understand better your problem but i am not sure why you have it.

I am thinking about a way to help debug it which is not making you do a lot of stuff. I will come back to you when it's ready.

If ou want you can check influxdb itself. http://192.168.59.104:8083(in your environment). User: admin, pass: admin. Select "nmon reports" database and do : 
![image](https://cloud.githubusercontent.com/assets/741174/7093135/e6e1dfb2-dfb6-11e4-9ba1-8c723601c3b3.png)

And run "list series" query : 

![image](https://cloud.githubusercontent.com/assets/741174/7093151/0d98c396-dfb7-11e4-8217-bb45cda4d313.png)

You should have a list of all data series from your nmon report.

It's only if you have time. Else i will provide a debug function in my nmon2influx binary.

Thanks

**Comment by ghost** [comment]
Hi ,

„list series” working properly and give similar results...;

Best regards
robert

![screen shot 2015-04-10 at 8 53 49 pm](https://cloud.githubusercontent.com/assets/3903647/7094780/d2f44d7e-dfc4-11e4-88bf-a1f65ef23820.png)

**Comment by adejoux** [comment]
Hello,

I found the problem.

It's in the configuration file for grafana. I define where to find the influxdb in it :

![image](https://cloud.githubusercontent.com/assets/741174/7104663/16fe6fea-e0f1-11e4-896b-acb37dc18a0e.png)

For now, the best solution is to edit it adn replace localhost by your docker container ip address in your docker container. The file is /www/grafana/config.js

grafana2 is a full stack application where it become easier to setup the data source. I think i will update my image with it later.
