### ISSUE TITLE
Dashboard creation - Grafana server config

### ISSUE THREAD

**Issue by rmoff** [adejoux/nmon2influxdb#12]
There doesn't seem to be anywhere to point nmon2influxdb at my grafana instance? In this example I'm running it's local and seems to work automagically, but it would be good to make this configurable and/or clarify in the documentation that it will look for grafana locally.

**Comment by adejoux** [comment]
Hello,

I am working on a configuration file to support all options. It would be easier to see what are all the options.
 For now, it's parameters to specify when running **nmon2influxdb dashboard** :  

```
nmon2influxdb dashboard file --help
NAME:
   nmon2influxdb dashboard file - generate a dashboard from a nmon file

USAGE:
   nmon2influxdb dashboard file [command options] [arguments...]

OPTIONS:
   --template, -t           optional json template file to use
   --file, -f               generate Grafana dashboard file
   --guser "admin"          grafana user
   --gpassword, --gpass "admin"     grafana password
   --gurl "http://localhost:3000"   grafana url
   --datasource "nmon2influxdb"     grafana datasource
```

So you have **_guser**_, **gpasswd** and **gurl** to configure how to access to grafana.
