### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by rmoff** [adejoux/nmon2influxdb#14]
Not sure if this should work, or I need some extra steps? I just copied & pasted the three lines from the README.md, as I saw that there's an updated codebase but the release version has not changed, so I thought I'd build it locally myself.

```
    ec2-user@controller:nmon () $ git clone https://github.com/adejoux/nmon2influxdb
    Cloning into 'nmon2influxdb'...
    remote: Counting objects: 196, done.
    remote: Total 196 (delta 0), reused 0 (delta 0), pack-reused 196
    Receiving objects: 100% (196/196), 2.02 MiB | 1.26 MiB/s, done.
    Resolving deltas: 100% (122/122), done.
    Checking connectivity... done.
    ec2-user@controller:nmon () $ cd nmon2influxdb
    ec2-user@controller:nmon2influxdb (master) $ go build
    nmon_dashboard.go:12:2: cannot find package "github.com/adejoux/grafanaclient" in any of:
            /usr/lib/golang/src/github.com/adejoux/grafanaclient (from $GOROOT)
            ($GOPATH not set)
    nmon_importer.go:10:2: cannot find package "github.com/adejoux/influxdbclient" in any of:
            /usr/lib/golang/src/github.com/adejoux/influxdbclient (from $GOROOT)
            ($GOPATH not set)
    helpers.go:8:2: cannot find package "github.com/codegangsta/cli" in any of:
            /usr/lib/golang/src/github.com/codegangsta/cli (from $GOROOT)
            ($GOPATH not set)
    ec2-user@controller:nmon2influxdb (master) $
```

**Comment by adejoux** [comment]
Hello,

You need to get my other libraries too. 
Maybe I should update the README here to make it more accurate.

It should be : 

```
go get -u github.com/adejoux/nmon2influxdb
```

It will get the dependencies. 

You will have everything available in **_$GO_PATH/src/github.com/adejoux/nmon2influxdb**_

If you can confirm if it's better like that I will update the README.

Thanks,

Alain

**Comment by rmoff** [comment]
Hi @adejoux,
I had to also add `export GOPATH=/u01`, after that, it all worked. Thanks!

**Comment by rmoff** [comment]
FWIW I had to set `GOPATH` rather than `GO_PATH` for it to work

**Comment by adejoux** [comment]
It's GOPATH :) I was not awake when writing this morning :) Thanks
