### ISSUE TITLE
build : influxdb.ListMeasurement undefined

### ISSUE THREAD

**Issue by adilnaimi** [adejoux/nmon2influxdb#2]
go buil fails, the build shows the following errorslog 

```
[root@c1bffe16ee9d nmon2influxdb]# go build
# _/nmon2influxdb
./nmon_list.go:28: influxdb.ListMeasurement undefined (type *influxdbclient.InfluxDB has no field or method ListMeasurement)
./nmon_stats.go:47: undefined: influxdbclient.BuildStats
```

my Go env is:

```
[root@c1bffe16ee9d nmon2influxdb]# go version
go version go1.4.2 linux/amd64
[root@c1bffe16ee9d nmon2influxdb]# go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by adejoux** [comment]
Hello,

I updated my influxdbclient library. I think the problem is from here.

Can you update it : 

```
go get -u github.com/adejoux/influxdbclient
```

Same for my grafanaclient library : 

```
go get -u  github.com/adejoux/grafanaclient 
```

Tell me if it's better.

Thanks,

Alain

**Comment by adejoux** [comment]
Sorry my bad

I tried on a vagrant system and reproduced the problem :   

```
vagrant@vm1:~/go/src/github.com/adejoux/nmon2influxdb$ go build
# github.com/adejoux/nmon2influxdb
./nmon_list.go:28: influxdb.ListMeasurement undefined (type *influxdbclient.InfluxDB has no field or method ListMeasurement)
./nmon_stats.go:47: undefined: influxdbclient.BuildStats
```

I forgot to push my modifications on github.

It's working now : 

```
vagrant@vm1:~/go/src/github.com/adejoux/nmon2influxdb$ go get -u github.com/adejoux/influxdbclient
vagrant@vm1:~/go/src/github.com/adejoux/nmon2influxdb$ go build

vagrant@vm1:~/go/src/github.com/adejoux/nmon2influxdb$ ./nmon2influxdb 
NAME:
   nmon2influxdb - upload NMON stats to InfluxDB database

USAGE:
   nmon2influxdb [global options] command [command options] [arguments...]

VERSION:
   0.5.0

AUTHOR(S):
   Alain Dejoux <adejoux@djouxtech.net> 

COMMANDS:
   import   import a nmon file
   dashboard    generate a dashboard from a nmon file or template
   stats    generate stats from a InfluxDB metric
   list     list InfluxDB metrics or measurements
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --server, -s "localhost" InfluxDB server and port
   --port, -p "8086"        InfluxDB port
   --db, -d "nmon_reports"  InfluxDB database
   --user, -u "root"        InfluxDB administrator user
   --pass "root"        InfluxDB administrator pass
   --debug          debug mode
   --tz, -t             timezone
   --help, -h           show help
   --version, -v        print the version
```

I updated too the binary on dropbox. 
I will publish a realese with packages for all platforms this week. 

Thanks

**Comment by adilnaimi** [comment]
@adejoux it works like a charm

```
[root@c1bffe16ee9d nmon2influxdb]# ./nmon2influxdb import /aix713_test1_150814_2100.nmon 
###############################
File /aix713_test1_150814_2100.nmon  imported !

[root@c1bffe16ee9d nmon2influxdb]# ./nmon2influxdb dashboard file /aix713_test1_150814_2100.nmon 
Grafana nmon2influxdb DataSource created.
Dashboard uploaded to grafana
```

thank you

**Comment by adilnaimi** [comment]
after successfully import nmon data and generate the dashboard.

the Grafana link to the server returns `Page not found (404)`
<img width="929" alt="screen shot 2015-08-19 at 01 04 33" src="https://cloud.githubusercontent.com/assets/1929963/9344011/5773bd82-460e-11e5-8a72-286997c9c858.png">

**Comment by adejoux** [comment]
First time I see this error. The dashboard can be completely wrong but normally it's displayed with nothing drawn. 

Can you try to create a dashboard manually ?

How did you install grafana and what is the version ?

**Comment by adejoux** [comment]
Sorry again. I introduced a bug today. I am fixing it.

**Comment by adejoux** [comment]
I fixed it. 

You can try it now. Sorry for the inconvenience. 

You can pull the code and build the package again or download it from dropbox.

Here what you should see when you upload a dashboard without importing data :
![image](https://cloud.githubusercontent.com/assets/741174/9345003/29e4d730-460d-11e5-8096-4381ca810ac1.png)

**Comment by adilnaimi** [comment]
yes it works :)

<img width="1279" alt="screen shot 2015-08-19 at 18 25 27" src="https://cloud.githubusercontent.com/assets/1929963/9360644/099093e6-46a0-11e5-8a1c-2f6d5f04c557.png">

**Comment by adejoux** [comment]
Great news :) Do you have data displayed in charts ?

For information, I released a "tested" version of nmon2influxdb today :  
https://github.com/adejoux/nmon2influxdb/releases

With some sample nmon reports and TOML template improvements(to define dashboard from text files).

**Comment by adilnaimi** [comment]
No, no data displayed in charts.

Yes, i have tested the new release the MacOS version one, I have successfully import nmon file from my mac to docker container which runs grafana+influxdb

```
./nmon2influxdb-macos-amd64 -s 192.168.99.100 import aix731_test_01.nmon
###########
File aix731_test_01.nmon imported !

./nmon2influxdb-macos-amd64 -s 192.168.99.100 dashboard file --gurl "http://192.168.99.100:3000" aix731_test_01.nmon
Dashboard uploaded to grafana
```

**Comment by adejoux** [comment]
I would say something is wrong with the datasource. Grafana is really quick.

Can you check the datasource definition :

![image](https://cloud.githubusercontent.com/assets/741174/9361384/7f5d98d0-469b-11e5-975d-f8ebf0488b96.png)

And run the "test connection" button :

![image](https://cloud.githubusercontent.com/assets/741174/9361442/bf1273ec-469b-11e5-9159-f00bae1fe604.png)

**Comment by adilnaimi** [comment]
oops, I do not have any db in datasource

Im trying to create a new one from the web console.
what is the password to connect to nmon_reports DB?

**Comment by adejoux** [comment]
Importing data in influxdb with nmon2influxdb will create the database for you normally. 

You can connect on http://192.168.99.100:8083. Default account is root, password is root.

**Comment by adejoux** [comment]
If you are stuck run : nmon2influxdb --debug import your_nmon_file. 
It's very verbose but the database creation should be in the first messages.

**Comment by adilnaimi** [comment]
I have created manually the DB connection from Grafana web-console.

And it works:

<img width="1232" alt="screen shot 2015-08-19 at 20 01 39" src="https://cloud.githubusercontent.com/assets/1929963/9363161/74fb1aa4-46ad-11e5-8cad-731dd59cf267.png">

**Comment by adejoux** [comment]
Really happy to hear that :dancers: 

I don't know why it was not created automatically. But it only need to be done one time. All dashboards will use the same datasource. 

Thanks for raising your hand. It help me to understand better what I need to explain to users :) 

Contact me if you have other questions. 

PS: in command line you can experiment  the stats command too : 

```
nmon2influxdb -s 192.168.99.100 stats -m CPU_ALL -s your_system
```

![image](https://cloud.githubusercontent.com/assets/741174/9363350/380a75ce-46a6-11e5-9434-5cafc2874c72.png)

**Comment by adilnaimi** [comment]
I think because of influxdb and grafana they run in the same Docker container, the Grafana data source should be from localhost:8086 and not fom docker machine IP.

**Comment by adejoux** [comment]
The thing is grafana manage both cases. You can choose if you want grafana to perform the request from your browser(direct mode) or proxying your query(proxy mode) and do it from grafana server.

The thing is when I create from scratch a container in kitematic and let nmon2influxdb create the datasource, it's working : 
![image](https://cloud.githubusercontent.com/assets/741174/9379946/248a64be-472d-11e5-86ec-8608d6bb6ed0.png)

But your idea is great. I could put it in proxy mode and it would use http://localhost:8086 : 

![image](https://cloud.githubusercontent.com/assets/741174/9379989/6e95222e-472d-11e5-8fe0-39bb5d4ac550.png)

It would simplify the command line. Thanks.

I open issue #3 for it.
