### ISSUE TITLE
build error : old influxdb client library import path

### ISSUE THREAD

**Issue by tonymaibz** [adejoux/nmon2influxdb#21]
I have installed Ubuntu 14.04 on influxDB v0.10.2 and Grafana, I download is complete, but go build look like fails.Installation process is as follows:

tony@ubuntu:~/go/src$ go get -u github.com/adejoux/nmon2influxdb
package github.com/influxdb/influxdb/client: code in directory /home/tony/go/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"
tony@ubuntu:~/go/src$ cd $GOPATH/src/github.com/adejoux/nmon2influxdb
tony@ubuntu:~/go/src/github.com/adejoux/nmon2influxdb$ go build
../influxdbclient/api.go:3:8: code in directory /home/tony/go/src/github.com/influxdb/influxdb/client expects import "github.com/influxdata/influxdb/client"
tony@ubuntu:~$ nmon2influxdb import ubuntu186_160322_1610.nmon
nmon2influxdb: command not found

**Comment by adejoux** [comment]
Hello,

Influxdata guys moved their repository from "github.com/influxdb/influxdb to "github.com/influxdata/influxdb"

I updated my github.com/adejoux/influxdbclient library to use the new path and tested it on Ubuntu 14.04 with a new GOPATH:

```
➜  ~ mkdir newgo
➜  ~ export GOPATH=/home/adejoux/newgo
➜  ~ go get -u github.com/adejoux/nmon2influxdb
➜  ~ cd newgo/src/github.com/adejoux/nmon2influxdb 
➜  nmon2influxdb git:(master) go build
➜  nmon2influxdb git:(master) ✗ ./nmon2influxdb 
NAME:
   nmon2influxdb - upload NMON stats to InfluxDB database

```

So it should be ok for you too.

Thanks

**Comment by adejoux** [comment]
Fixed in https://github.com/adejoux/influxdbclient/commit/9639a4c6cd9fa2dbe2688b76cde06835245337b0
