### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by n3biot** [adejoux/nmon2influxdb#25]
Hello,

First thank you for your very usefull tool !

Im trying to compile nmon2influxdb on Windows but I have a problem with 

```
 go build
# github.com/adejoux/nmon2influxdb
.\nmon_importer.go:71: influxdbLog.ReadLastPoint undefined (type *influxdbclient.InfluxDB has no field or method ReadLastPoint)
.\nmon_importer.go:82: influxdbLog.ReadLastPoint undefined (type *influxdbclient.InfluxDB has no field or method ReadLastPoint)
```

I can't find ReadLastPoint on influxdbclient. 
Could you help me.

Another minor thing : 

```
go get -u github.com/adejoux/nmon2influxdb
# cd C:\CPPPERFS\gowork\src\github.com\adejoux\nmon2influxdb; git submodule update --init --recursive
fatal: No url found for submodule path 'docs/themes/darkdoc' in .gitmodules
package github.com/adejoux/nmon2influxdb: exit status 128
```

I managed to go further by removing the '-u' 

Thank you again
n3biot

**Comment by adejoux** [comment]
Hello,

Thanks. I forgot to add a .gitmodules to list sub project. It's fixed. 

And I didn't push my latest update to influxdbclient. It's done now. 

I tested and everything seems fine now. Let me know if you have another issue.

Thanks :)

Alain

**Comment by n3biot** [comment]
Merci

**Comment by adejoux** [comment]
It's me which should say thanks. So thanks. :)
