### ISSUE TITLE
retention policy not found: default on import

### ISSUE THREAD

**Issue by awilson77584** [adejoux/nmon2influxdb#26]
Hi.  Thank you for sharing your tool.  I attempted to import the test nmon files into my database and I get a message that 17956 points are imported but it is followed by an error stating that there is not default RP.

I created an RP with the name default and made it the default RP, but I still get the error.  No measurements are created.

Any thoughts?

Thanks!
File linux_150818_1024.nmon imported : 17956 points !
2016/11/02 16:22:57 {"error":"retention policy not found: default"}

**Comment by inxonic** [comment]
Seems to be related to https://github.com/influxdata/influxdb/issues/6825

It worked by creating the policies manually:

```
create retention policy "default" on nmon_reports duration 0d replication 1 default
create retention policy "default" on nmon2influxdb_log duration 1d replication 1 default
```

**Comment by adejoux** [comment]
Hello,

Sorry I missed the first message. inxonic is correct. The problem is related to this issue. I will fix it this evening. 

Thanks

Alain

**Comment by adejoux** [comment]
Hello,

I released a new version fixing the issue. 

Thanks :) 

Special thanks to @inxonic . It was very helpful :)

**Comment by awilson77584** [comment]
Thank you.  I'll download the new version.
