### ISSUE TITLE
Adding Tags to Measurements

### ISSUE THREAD

**Issue by awilson77584** [adejoux/nmon2influxdb#27]
Hi.  Thanks for the earlier help.  You've written a nice tool.  
I'm new to reading Go and identifying the logic.  Is there a way to add tags to the individual measurements?  Is there a set of identifiers in an NMON file that are used to dynamically create measurements?  I see that you use name to hold the metric type and host to hold the hostname.

We are using Telegraf to add tags identifying the data center, business class, application service, etc for our Windows and Linux hosts.

What are your recommendations for a similar use case for AIX hosts?

Thanks!
Alan

**Comment by adejoux** [comment]
Hello,

You are correct. I use for most measurements only two tags host and name. The only exception is TOP where I add top, command and pid tags. 

For example, for CPU_ALL, in nmon file we have first this line:

```
CPU_ALL,CPU Total vio1_g2_46cfp,User%,Sys%,Wait%,Idle%,Busy,PhysicalCPUs
```

I split the line and use CPU_ALL  for measurement name.
User%, Sys%, Wait%, Idle%, Busy, PhysicalCPUs will be values for the name tag. 

The next line in nmon for CPU_ALL will be:

```
CPU_ALL,T0001,19.9,44.8,0.1,35.3,,8
```

So i will store 19.9 in measurement CPU_ALL with name tag equals to "User%". 
I also add the host tag from this nmon line:

```
AAA,host,myserver
```

Adding other tags can be a good idea. I could add it as an optional parameter. Something like that:

```
nmon2influxdb import --tags "datacenter=DC1,server=FRAME1" myserver.nmon
```

But maybe you don't need to add this tags to all measurements but just some of them. So it could be:

```
nmon2influxdb import --tags "CPU_ALL:datacenter=DC1,server=FRAME1" myserver.nmon
```

Let me know what behavior you would like to have.

Alain

**Comment by awilson77584** [comment]
Having global and and tags for different measures options would be ideal.  Are you thinking that tagging could be set in the configuration file as well?  The method used in telegraf would be very useful and even the ability to use referenced per-server filters and tags in an /etc/nmon2influxdb/cfg.d directory would extend the flexibiliity.  Our use case is to tag data from 250+ lpars across 9 different frames.  
I'm trying to learn Go, but I'm much more of a hack than a professional programmer.  I hope to be able to add eventually.

Thanks!

**Comment by adejoux** [comment]
Hello,

Good idea to try to replicate telegraf tagging system, I will look at it.

I am not sure if nmon2influxdb in the current state is a good fit for your use case. Storing nmon data from 250+ partitions every day will make a really big database. You can skip some metrics(like individual disks) but I think it's still not ideal. 

I am working to allow the tool to load data from the HMC itself instead of nmon files. It would make it easier to supervise so many partitions. nmon files would be only used for performance analysis. I hope to release a first draft in few days. 

Anyway I will implement the tagging system, it will be a good addition. 

Thanks

**Comment by awilson77584** [comment]
You are a hero.  Is is it possible to capture lpar disk utilization information from the HMC?  We use LPAR2RRD, but it doesn't have disk data.  It also doesn't have memory utilization at the LPAR level.  It just reports server pool information.

I was working on adapting lpar2rrd to write out in line protocol, but when I found your tools, it seemed to be a much better approach.  Lpar2rrd writes out from every separate metric calculation module instead of from a common writer module and it was proving to be messy to make certain that I caught them all.

On the nmon file front, we are just using the Nagios nrpe agents that we already have in place on each server to rsync to a collector server where we run nmon2influxdb to pick up the delta perf data.  If the load became difficult for a single nmon2influxdb instance, that would give me a good reason to use docker or something to run multiple instances against the nmon data files. That way we let Nagios handle the scheduling and error reporting. You have an excellent solution for recognizing what has already been added.  Disk is cheap, right? //smile.

Thanks!
Alan

**Comment by adejoux** [comment]
Hello :) 

I pushed my initial work on HMC PCM data on github. It's still early phase so it's in a dedicated branch called hmc. It's issue #28. 

It's working but I didn't enable the dashboard creation and the code is not so great. I can do better ;) 

I pushed it mostly to show you and others interested in what direction I am going for HMC metrics. I also moved a lot of files to try to clean up the code. I think it's making it easier to understand.

It's mostly disk space related from what I have seen. I could perform data aggregation with InfluxDB continous query but it would become a lot more complicated. And continuous query when loading many nmon files can be a problem. 

Anyway I think adding HMC informations can be great and will not remove the interest of loading nmon files too. 

Thanks for your comment on the incremental update. I spent some time on it.  :)

Alain

**Comment by adejoux** [comment]
Hello,

New release 2.1.0 includes custom tags. Let me know what you think about it :)

**Comment by awilson77584** [comment]
We will download it and get right back to you.  Thanks!

Alan

**Comment by adejoux** [comment]
thanks. Closing the issue for now :)
