### ISSUE TITLE
Error status code: 401

### ISSUE THREAD

**Issue by sbrech** [adejoux/nmon2influxdb#30]
THX for your work but I have a problem to use your code.

I received the following output:
```
# /opt/nmon2influxdb/nmon2influxdb-linux-amd64 --debug hmc import                                                │[root@epinflux01-bs log]# tail -f /var/log/messages
[{[{databases map[] [name] [[_internal] [server_power]] <nil>}] }]                                                                   │Nov 23 11:00:31 epinflux01-bs influxd: [httpd] 172.17.68.32 - hmc [23/Nov/2016:11:00:31 +0100] "GET /query?db=_internal&q=show+databases%
ALTER RETENTION POLICY "autogen" ON "nmon2influxdbHMC" DURATION 60d REPLICATION 1 DEFAULT                                            │3Bdrop+database+nmon2influxdbHMC%3B HTTP/1.1" 200 233 "http://10.76.64.9:8083/?" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36
2016/11/23 11:00:06 Error status code: 401
```
The 'nmon2influxdbHMC' was created  inside the influxdb so the config should be correct. I can also use the influxdb Webgui to  
```
ALTER RETENTION POLICY "autogen" ON "nmon2influxdbHMC" DURATION 60d REPLICATION 1 DEFAULT
```
but your code again stop at this point.

Do you have some hints for me?

regards,
Sascha

**Comment by adejoux** [comment]
Hello,

Thanks for your feedback. 
Can you give me your influxdb version ? Code 401 is mostly related to authentication problem but like you said the database was created. I will download the same version and test it. 

Thanks

**Comment by adejoux** [comment]
Hello,

I forgot to say it but remove **hmc_data_retention** in **~/.nmon2influxdb.cfg** for a quick fix. It will allows you to go further. 

I am also surprised to not see the database in your debug output. It was the first run? 

A standard output should be:

``````
/Users/adejoux/go/bin/nmon2influxdb --debug hmc import            

[{[{databases map[] [name] [[_internal] [nmon_reports] [nmon2influxdb_log] [nmon2influxdbHMC]] <nil>}] }]
ALTER RETENTION POLICY "autogen" ON "nmon2influxdbHMC" DURATION 60d REPLICATION 1 DEFAULT
Getting list of managed systems
...
```````

**Comment by sbrech** [comment]
Hi,

I removed the 'hmc_data_retention' line but no success.
```
# /opt/nmon2influxdb/nmon2influxdb-linux-amd64 --debug hmc import                                                │Nov 23 11:00:56 epinflux01-bs influxd: [query] 2016/11/23 11:00:56 CREATE DATABASE nmon2influxdbHMC
[{[{databases map[] [name] [[_internal] [server_power] [nmon2influxdbHMC]] <nil>}] }]                                                │Nov 23 11:00:56 epinflux01-bs influxd: [httpd] 172.19.161.174 - hmc [23/Nov/2016:11:00:56 +0100] "GET /query?db=nmon2influxdbHMC&q=create
2016/11/23 12:04:47 Error status code: 401
```
I use influxdb-1.0.2-1.x86_64 directly from InfluxDB and yes it was the first run.

regards,
Sascha

**Comment by adejoux** [comment]
Hello, 

I finally found it. It's not related to influxDB at all. It's your credentials for your hmc. 

I installed the same version of InfluxDB. If you enable authentication and set the wrong password you have: 

````
2016/11/23 13:54:31 authorization failed
``````

But if I change my hmc_password line in the configuration file to a wrong password:

``````
[{[{databases map[] [name] [[_internal] [nmon_reports] [nmon2influxdb_log] [nmon2influxdbHMC]] <nil>}] }]
2016/11/23 13:53:55 Error status code: 401
```````

You need to update **hmc_user** and **hmc_password** in your configuration file. 

Sorry for that, it's really a poor error message here. I will fix it. 


Thanks,

Alain

**Comment by adejoux** [comment]
With fix #30, new error message will be:

``````
nmon2influxdb hmc import  
2016/11/23 14:14:23 HMC authentication error: 401 Unauthorized
````````

If hmc server name is wrong, it will be:

``````
 nmon2influxdb hmc import --hmc foobar
2016/11/23 14:14:41 HMC error sending auth request Put https://foobar:12443/rest/api/web/Logon: dial tcp: lookup foobar: no such host
```````

**Comment by sbrech** [comment]
should work now, code is currently running and pushing data to the influx.
Is hscroot recommended? Before, I used a extra User with 'hmcviewer' role.

thx for your support.

**Comment by adejoux** [comment]
Great ☺. I will check this evening what is the minimum role needed.

**Comment by sbrech** [comment]
Ok, my fault. A HMC User with the 'hmcviewer' Role is working.

**Comment by adejoux** [comment]
Great news ☺. Everything is working for you now ?

**Comment by sbrech** [comment]
Everything fine know, thank you.

Would it be possible to code a switch for managed system info only? A complete hmc import (manged systems and LPARs) took 20 in our environment minutes, which is ok for the LPARS but it would be nice to get the data from the Hardware faster.

regards,
Sascha

**Comment by adejoux** [comment]
Hello,

Good news. Your point is right. I opened issue #31 to manage it. 

Closing this one. 
Thank you.
