### ISSUE TITLE
Disk %Busy displays same data as Disk IO Reads per second

### ISSUE THREAD

**Issue by bourqued1** [adejoux/nmon2influxdb#33]
Hi Alain,

"Disk %Busy" seems to display "Disk IO Reads per second". I compared an imported nmon file between the Grafana and NMON Visualiser.

Thanks!

**Comment by adejoux** [comment]
Hello,

You are completely right. I took DISKRIO instead of DISKBUSY in the  report generation.

It should be:

![image](https://cloud.githubusercontent.com/assets/741174/20805380/a4b371f4-b7f6-11e6-9096-f1d32439415e.png)

It will be fixed in next release. It's already patched.

Thanks

**Comment by adejoux** [comment]
I updated the linux binary in release 2.1.0. It contains the fixed version.

Thanks
