### ISSUE TITLE
Not able to execute Rel 2.1.0, but able to execute 2.0.1

### ISSUE THREAD

**Issue by awilson77584** [adejoux/nmon2influxdb#34]
We receive a "cannot execute binary file" error with the 2.1.0 release.  2.0.1 does execute.

Our system type an version:
 uname -a
Linux LUSRCDNNV01.fossil.com 3.10.0-327.13.1.el7.x86_64 #1 SMP Mon Feb 29 13:22:02 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
 and
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

Is this a Go library issue?  I'm not able to run a yum update until a change is resolved.

Thanks!

**Comment by adejoux** [comment]
Hello,

It's a mistake in my build, it's not a linux binary but a macos one.

I updated the package in the release 2.1.0.

Thanks,

Alain

**Comment by awilson77584** [comment]
Thanks!!
