### ISSUE TITLE
No datapoint graphs: influxdb and grafana in two separated dockers

### ISSUE THREAD

**Issue by adilnaimi** [adejoux/nmon2influxdb#4]
I want to separate influxdb from grafana by running each service on a dedicated container.

influxdb docker:

```
docker run -d --name influxdb -p 8083:8083 -p 8086:8086 --expose 8090 --expose 8099 adil/influxdb
```

grafana

```
docker run --rm -v /Users/adil/000_aix/data:/var/lib/grafana \
    -e "GF_SERVER_ROOT_URL=http://grafana.adil.me"  \
    --link influxdb:influxdb -p 3000:3000 adil/grafana
```

everything works fine, connection between grafana and influxdb is ok:
<img width="1233" alt="screen shot 2015-08-20 at 20 24 44" src="https://cloud.githubusercontent.com/assets/1929963/9390494/2b945b32-477a-11e5-82a8-47e86610f9cd.png">

I can import data:

```
➜  ~ nmon2influxdb -s 192.168.99.100 import aix731_test.nmon
###########
File aix731_test.nmon imported !
➜  ~  nmon2influxdb dashboard file --gurl "http://192.168.99.100:3000" aix731_test.nmon
Dashboard uploaded to grafana
➜ nmon2influxdb dashboard file --gurl "http://192.168.99.100:3000" -f aix731_test.nmon
Writing GRAFANA dashboard: aix731_test_dashboard
```

But It seems that graphs were not generated:
<img width="1278" alt="screen shot 2015-08-20 at 20 30 10" src="https://cloud.githubusercontent.com/assets/1929963/9390512/494f733c-477a-11e5-9f57-f4d48e3bef8f.png">

I have tested with the direct access too, but the same issue as with proxy mode.

**Comment by adilnaimi** [comment]
If I'm not mistaken, the server variable variable if it can have two value, like influxdb_server and grafana_server:

https://github.com/adejoux/influxdbclient/blob/master/api.go#L25

during the data import, the both servres can be added seprately, something like:

```
nmon2influxdb --influxdb_host192.168.99.100 --grafana_host 172.16.1.100 import aix731_test.nmon
```

**Comment by adejoux** [comment]
I need to try this setup. All seems fine so far. If the datasource test work, it should be able to fetch data from influxdb.

I am wondering if data was really imported. Can you try on influxdb admin console "show measurements" and "show series" to see if data are here ?

For now te server variable is used in main.go only for influxdb: 
https://github.com/adejoux/influxdbclient/blob/master/api.go#L172

Grafana is not contacted during the import. Your docker configuration is good. So I really need to test your setup to say what is wrong here.

**Comment by adilnaimi** [comment]
i think data was imported:

```
# docker exec -it influxdb bash
root@9b3f998df85f:/# ps -ef                 
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:05 ?        00:00:00 /bin/bash /run.sh
root         9     1  0 17:05 ?        00:00:13 /opt/influxdb/influxd -config=/config/config.toml
root        37     0  0 17:58 ?        00:00:00 bash
root        46    37  0 17:58 ?        00:00:00 ps -ef
root@9b3f998df85f:/# /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.2.1
InfluxDB shell 0.9.2.1
>  show databases 
name: databases
---------------
name
nmon_reports

> use nmon_reports
Using database nmon_reports
> show measurements  
name: measurements
------------------
name
CPU_ALL
DISKAVGRIO
DISKAVGWIO
DISKBSIZE
DISKBUSY
DISKREAD
DISKREADSERV
DISKRIO
DISKRXFER
DISKSERV
DISKWAIT
DISKWIO
DISKWRITE
DISKWRITESERV
DISKXFER
FILE
IOADAPT
JFSFILE
JFSINODE
LPAR
MEM
MEMNEW
MEMUSE
NET
NETERROR
NETPACKET
NETSIZE
NFSCLIV2
NFSCLIV3
NFSSVRV2
NFSSVRV3
PAGE
PCPU_ALL
POOLS
PROC
PROCAIO
SCPU_ALL
VM
> show series 
name: CPU_ALL
-------------
_key                        host        name
CPU_ALL,host=aix731_test,name=User%       aix731_test   User%
CPU_ALL,host=aix731_test,name=Sys%        aix731_test   Sys%
CPU_ALL,host=aix731_test,name=Wait%       aix731_test   Wait%
CPU_ALL,host=aix731_test,name=Idle%       aix731_test   Idle%
CPU_ALL,host=aix731_test,name=PhysicalCPUs\   aix731_test   PhysicalCPUs 


name: DISKAVGRIO
----------------
_key                        host        name
DISKAVGRIO,host=aix731_test,name=hdisk3   aix731_test   hdisk3
DISKAVGRIO,host=aix731_test,name=hdisk4   aix731_test   hdisk4
DISKAVGRIO,host=aix731_test,name=hdisk6   aix731_test   hdisk6
DISKAVGRIO,host=aix731_test,name=hdisk0   aix731_test   hdisk0
DISKAVGRIO,host=aix731_test,name=hdisk2   aix731_test   hdisk2
DISKAVGRIO,host=aix731_test,name=hdisk5   aix731_test   hdisk5
DISKAVGRIO,host=aix731_test,name=hdisk1   aix731_test   hdisk1
DISKAVGRIO,host=aix731_test,name=hdisk7   aix731_test   hdisk7
DISKAVGRIO,host=aix731_test,name=hdisk8   aix731_test   hdisk8


name: DISKAVGWIO
----------------
_key                        host        name
DISKAVGWIO,host=aix731_test,name=hdisk3   aix731_test   hdisk3
DISKAVGWIO,host=aix731_test,name=hdisk4   aix731_test   hdisk4
DISKAVGWIO,host=aix731_test,name=hdisk6   aix731_test   hdisk6
DISKAVGWIO,host=aix731_test,name=hdisk0   aix731_test   hdisk0
DISKAVGWIO,host=aix731_test,name=hdisk2   aix731_test   hdisk2
DISKAVGWIO,host=aix731_test,name=hdisk5   aix731_test   hdisk5
DISKAVGWIO,host=aix731_test,name=hdisk1   aix731_test   hdisk1
DISKAVGWIO,host=aix731_test,name=hdisk7   aix731_test   hdisk7
DISKAVGWIO,host=aix731_test,name=hdisk8   aix731_test   hdisk8


name: DISKBSIZE
---------------
_key                        host        name
DISKBSIZE,host=aix731_test,name=hdisk3    aix731_test   hdisk3
DISKBSIZE,host=aix731_test,name=hdisk4    aix731_test   hdisk4
DISKBSIZE,host=aix731_test,name=hdisk6    aix731_test   hdisk6
DISKBSIZE,host=aix731_test,name=hdisk0    aix731_test   hdisk0
DISKBSIZE,host=aix731_test,name=hdisk2    aix731_test   hdisk2
DISKBSIZE,host=aix731_test,name=hdisk5    aix731_test   hdisk5
DISKBSIZE,host=aix731_test,name=hdisk1    aix731_test   hdisk1
DISKBSIZE,host=aix731_test,name=hdisk7    aix731_test   hdisk7
DISKBSIZE,host=aix731_test,name=hdisk8    aix731_test   hdisk8
```

**Comment by adejoux** [comment]
yes. Definitely imported :) 

And when you try in the query editor of grafana you don't see anything ? 

I build a vm to try your setup currently.

**Comment by adilnaimi** [comment]
oops sorry it was my mistake, I was configured the DB name as "db2" and not "nmon_reports".

I have changed DB name with the correct database name and its working

**Comment by adejoux** [comment]
good to hear :) I am closing the issue :) 

I like your docker setup :)

**Comment by adejoux** [comment]
@adilroot if you want you could add your advanced docker setup in the readme. It could go in a "advanced docker configuration" section :)

**Comment by adilnaimi** [comment]
@adejoux I have pushed docker_advanced_setup in this fork https://github.com/adilroot/nmon2influxdb/tree/master/docker_setup

Once I will finish the README, I will make a pull request to your repo, you can check and merge

**Comment by adejoux** [comment]
Really great work :) I was only thinking about adding some how to in the README. Your solution is doing a lot more :)

You used a lot of variables so it's pretty flexible. I would only add one for the volume in https://github.com/adilroot/nmon2influxdb/blob/master/docker_setup/start.sh#L54 to let the user choose another directory for his data. 

And we can use the grafana official docker image directly too(grafana/grafana). Not sure here because it's not an automated build. Up to you :) 
Thanks

**Comment by adilnaimi** [comment]
@adejoux Thank you for your feedback.

sorry for the delay, Im currently diving in a prod PowerHA migration from 6.1 to 7.1.3 which It's taking all my time.

Once I have time i will back to you

**Comment by adejoux** [comment]
@adilroot no rush here :) take your time :)
