### ISSUE TITLE
Problem with default retention in influxdb 1.1.1

### ISSUE THREAD

**Issue by Architecttheday** [adejoux/nmon2influxdb#44]
Hi,
Trier to use nmon2influxdb with influxdb 1.1.1
When importing a new server with nmon2influxdb import nmon-file I got the error that the default retention policy is not found. Ich found out that influxdb changed the parameter. 
Can you please add support for influxdb 1.1.1 and up.
```
# ./nmon2influxdb import DBA1_170130_0000.nmon
2017/01/31 10:29:12 {"error":"retention policy not found: default"}
```
Thanks

**Comment by adejoux** [comment]
Hello,

I updated nmon2influxdb to fix this issue in issue #26. Did you use the latest version ?(2.1.2). 

I tested on a vanilla influxdb 1.2.0 installation and it's working:

```
 nmon2influxdb import vio1_020316.nmon 
2017/01/27 23:35:41 Using configuration file /home/adejoux/.nmon2influxdb.cfg
2017/01/27 23:35:41 Updating  autogen retention policy to keep only the last 2000d days. Timestamp based.
######################
```

If you use the latest versin and you have the issu, could you try to run it in debug mode:

```
./nmon2influxdb --debug import DBA1_170130_0000.nmon
```

Thanks,

Alain

**Comment by Architecttheday** [comment]
Hi Alain,
thanks for the feedback. My fault. I downloaded a old version of nmon2influxdb. with 2.1.2 it works fine.
Thanks,
Sascha

**Comment by adejoux** [comment]
Great news :) Thanks.
