### ISSUE TITLE
suppport for influxdb 1.2.0-1

### ISSUE THREAD

**Issue by adilnaimi** [adejoux/nmon2influxdb#46]
I have built a new server to test influxdb 1.2.0-1 using the same data I'm already using for influx 0.9

but seems grafana dashbord can't load data from influxdb 1.2

![image](https://cloud.githubusercontent.com/assets/1929963/22626911/72749d84-ebc8-11e6-8af9-4a8a9be2c259.png)

PS: I'm using gravana 4.1.1-1484211277

**Comment by adejoux** [comment]
Hello,

I tested it on a new vm and nmon2influxdb is working with influxdb 1.2.0 and grafana 4.1.1. 

Can you check your datasource configuration ?

![image](https://cloud.githubusercontent.com/assets/741174/22628128/f3422660-ebce-11e6-86e2-bda98ce09c92.png)

And I am using influxdb 1.2.0:
![image](https://cloud.githubusercontent.com/assets/741174/22628151/4bf0041c-ebcf-11e6-8d6d-b80648778b8c.png)

Save and test should display success. Something which can have changed is the way grafana is connecting to influxdb. Here it's direct but if it's not working you should try proxy. 

Let me know what happens. 

Also use version 2.1.3. I fixed a huge bug in nmon import performance.

Thanks,

Alain

**Comment by adilnaimi** [comment]
Actually, I did not configure garafana datasource, I let nmon2influxd autoconfigure and by default it set to proxy.

I have manually change it to proxy and the connection it's working fine, but still no metrics graphs showing on grafana, it might be an error in my config I'll check before closing the issue. 

PS: Regarding the version 2.1.3, Yes, This exercise was about testing 2.1.3 with newer grafana and influxdb version

**Comment by adilnaimi** [comment]
After changing grafana connection to mode proxy, it's working fine

![image](https://cloud.githubusercontent.com/assets/1929963/22637849/864899cc-ec55-11e6-8333-a90093d40b39.png)

I have used `grafana_access="proxy"` in my ~/..nmon2influxdb.cfg

**Comment by adejoux** [comment]
Great news. Maybe I should switch the default value to "proxy"... 

Closed.

**Comment by adilnaimi** [comment]
Thanks for the awesome support.

Not sure if putting default to "proxy" will help in all cases, my case is grafana and influx are running as a process (RPM) packages, I'm not sure about the docker case when running grafana in a container and link it to influx container
