### ISSUE TITLE
influxdb url https access failed

### ISSUE THREAD

**Issue by adilnaimi** [adejoux/nmon2influxdb#48]
I have to enable inluxdb ssl for data transfer encryption, but nmob2influxdb can't connect to the url when adding https to the influxdb_server  in `~/.nmon2influxdb.cfg` 
```
/data/nmon/bin/nmon2influxdb import LPAR71_TEST_170404_0000.nmon
2017/04/04 15:09:22 Using configuration file /root/.nmon2influxdb.cfg
2017/04/04 15:09:22 Get http://https/ping: dial tcp: lookup https: no such host
```

my config
```
grep influxdb_server  /root/.nmon2influxdb.cfg
influxdb_server="https://influxserver.smrc.domain.org"

```

**Comment by adejoux** [comment]
I admit I never tested the ssl access. I will check it and come back to you.

Alain

**Comment by adejoux** [comment]
Hello,

The new release should work for you. Let me know if you still have an issue.

Thanks :)

Alain

**Comment by adilnaimi** [comment]
I confirm the new version is working perfectly with influxdb ssl enabled

Thank you very much 

the issue can be closed

**Comment by adejoux** [comment]
Thanks
