### ISSUE TITLE
Possibility to change delimiter

### ISSUE THREAD

**Issue by thaentzler** [adejoux/nmon2influxdb#50]
Hello, 

Is it possible to make an evolution of this tool to integrate CSV mode nmon with ";" delim ?

**Comment by adejoux** [comment]
Hello,

It's a good idea. I will implement it.

Thanks,

Alain

**Comment by adejoux** [comment]
Hello,

Could you explain how you generate your nmon file ? Because I am not sure if only changing the delimiter will be enough to import the file.

Thanks,

Alain

**Comment by thaentzler** [comment]
Hello, 

    Sure, in fact it was the local delimiter who is changed (to be able to analyse the nmon in the old xls file ;) )
    So basically, all the "," is changed to ";" and the "." is changed to ",". 
    So basically we used a sed to replace all the , in . an after the ; to , to be able to upload them in influx :)

Thanks,

**Comment by adejoux** [comment]
Hello,

Sorry for the late answer, I was really busy. I don't see a problem by adding a parameter to change the delimiter but you also change dot by comma. It seems to me to be very specific. 
Are you ok if I only add the delimiter parameter?

Regards,

Alain

**Comment by thaentzler** [comment]
No problem :) 

i think it doesn't cause any trouble on import if number is delimited by , or . so for me it's ok.

basically on a previous tools used to parsed Nmon, we just detect the delimiter on first line and adapt the parsing after.

**Comment by adejoux** [comment]
Hello,

Auto detection was a great idea :) I implemented it. It's changing a lot of things in my code so I will not release it yet. I am testing it in my environment for some days.

But you can try it if you want. I attach the binary for linux here. 
[nmon2influxdb.zip](https://github.com/adejoux/nmon2influxdb/files/975656/nmon2influxdb.zip)

It's also including the fix for nan values.

Let me know if it's working for you.

Thanks,

Alain

**Comment by thaentzler** [comment]
Hello, 

 Thanks a lot for your answer and reactivity ! unfortunatelly it does not work as expected. 

Point are imported, but since integer delimiter is not correct, i've got no correct data ....

**Comment by adejoux** [comment]
Hello,

I just checked if errors happenend :( 

You are right, golang is not playing nicely with comma values: https://play.golang.org/p/duzvnI7l5_
Problem is  I don't find a way to specify the locales to use here.

How your previous tool managed it?

A quick solution would be to encapsulate nmon2influxdb in a script like that:
```
nmonfile=$1
sed 's/,/\./' $nmonfile > temp.nmon
nmon2influxdb import temp.nmon
rm temp.nmon
```

Regards,

Alain

**Comment by thaentzler** [comment]
It was a JS script : 

basically it detect the delimiter at the first line : 

// Detecting field separator
		var separator = ( sample.length > 2 ) ? ";" : ",";
		self.postMessage({ type : "debug", message : "using '"+separator+"' as field separator" });

and then for each line we got this replacement :

			if ( separator == ";" ) { line = line.replace(',','.') }
			var columns = line.split(separator);

for the script that's what i do for the moment :) a double sed ;)

**Comment by adejoux** [comment]
Hello,

I improved the solution. You can test it here.
Honestly I don't think it should be implemented in the tool itself but it was fun to implement automatic delimiter detection and without the comma substitution it would be useless. So why not :)


Alain
[nmon2influxdb.gz](https://github.com/adejoux/nmon2influxdb/files/976482/nmon2influxdb.gz)

**Comment by thaentzler** [comment]
It Works, and it Rocks :)

**Comment by thaentzler** [comment]
En apparté, j'ai corrigé un peu ton dashboard pour inclure les mesure linux
et la vue sur les dedicated pool :

Si ca peut te servir !


2017-05-04 16:39 GMT+02:00 adejoux <notifications@github.com>:

**Comment by adejoux** [comment]
Great. :)

Oui ça m'intéresse. :)

**Comment by thaentzler** [comment]
Here it is : 

[AIX NMON report-1493910237925.json.txt](https://github.com/adejoux/nmon2influxdb/files/976694/AIX.NMON.report-1493910237925.json.txt)

**Comment by adejoux** [comment]
Merci :) Je regarde demain :)
