### ISSUE TITLE
Error on "nan" value under JFS

### ISSUE THREAD

**Issue by thaentzler** [adejoux/nmon2influxdb#51]
Hello Sorry to bother again :), i have discover some error when value is "nan" on JFS (when using NFS for example) : 

JFSFILE,T0001,27.6,4.9,42.6,41.4,66.9,30.4,2.5,55.3,10.2,54.3,6.6,48.3,7.6,2.9,39.8,55.0,17.9,4.1,34.1,4.5,29.2,0.0,35.0,40.8,40.3,3.1,29.3,77.7,8.9,3.4,30.3,49.4,45.6,87.4,2.7,3.3,5.7,nan,76.3,0.0

2017/04/24 13:45:59 Error:  NaN is an unsupported value for field value
2017/04/24 13:45:59 Error:  NaN is an unsupported value for field value
2017/04/24 13:45:59 Error:  NaN is an unsupported value for field value
2017/04/24 13:45:59 Error:  NaN is an unsupported value for field value

it crashed the import of file.

**Comment by adejoux** [comment]
Hello,

You don't bother me at all. It's a great find. :) Thanks.

I will fix it.

Alain

**Comment by adejoux** [comment]
Hello,

I fixed it in the code. I am waiting to see if I can include the issue #50 before releasing the new version.

Regards,

Alain
