### ISSUE TITLE
HMC Import Failing

### ISSUE THREAD

**Issue by rodypr06** [adejoux/nmon2influxdb#52]
Hi,

I am trying to import HMC data into Influxdb but I keep getting this error: Help please!

2017/05/16 13:50:26 MANAGED SYSTEM SERVER-8408-E8E-SN215150W
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/adejoux/nmon2influxdb/hmc.Import(0xc4200cbe00)
        /root/go/src/github.com/adejoux/nmon2influxdb/hmc/import.go:115 +0x7a4b
github.com/codegangsta/cli.HandleAction(0x809d60, 0x8ce268, 0xc4200cbe00, 0xc420016f00, 0x0)
        /root/go/src/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/codegangsta/cli.Command.Run(0x8b6dcc, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8bc8ad, 0x13, 0x0, ...)
        /root/go/src/github.com/codegangsta/cli/command.go:207 +0xb6e
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200f49c0, 0xc4200cbb80, 0x0, 0x0)
        /root/go/src/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/codegangsta/cli.Command.startApp(0x8b5dcb, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8b9ea6, 0xd, 0x0, ...)
        /root/go/src/github.com/codegangsta/cli/command.go:293 +0x8a3
github.com/codegangsta/cli.Command.Run(0x8b5dcb, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8b9ea6, 0xd, 0x0, ...)
        /root/go/src/github.com/codegangsta/cli/command.go:93 +0x14c3
github.com/codegangsta/cli.(*App).Run(0xc4200f4680, 0xc420010150, 0x3, 0x3, 0x0, 0x0)
        /root/go/src/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()
        /root/go/src/github.com/adejoux/nmon2influxdb/main.go:317 +0x22e5

**Comment by adejoux** [comment]
Hello,

Can you run the command in debug mode and send me the file:

````
nmon2influxdb --debug-file nmon2influxdb.debug hmc import
````
Regards,

Alain

**Comment by rodypr06** [comment]
Hi,

I have attached the debug file. We currently have 4 managed systems ( 1
8202 and 3 8408's) with 51 Lpar's.

Thanks!

**Comment by adejoux** [comment]
Sorry I missed your answer and I do'nt see any attached file here

**Comment by rodypr06** [comment]
OK, sorry about that, I attached it to the email. Here it is, Hope it works now.

Thanks!

[nmon2influxdb-debug-file.txt](https://github.com/adejoux/nmon2influxdb/files/1019102/nmon2influxdb-debug-file.txt)

**Comment by adejoux** [comment]
Hello,

It's perfect now. Thanks. I know why it's failing. In your HMC version you do'nt have transmittedbytes metrics and it's failing. It's in the latest releases only and I didn't check if it was available.  I will update the code to fix it.

Regards,

Alain

**Comment by rodypr06** [comment]
Thanks a lot!

**Comment by adejoux** [comment]
Hello,

Can you test this version and let me know if it's working ?

Thanks,

Alain
[nmon2influxdb.zip](https://github.com/adejoux/nmon2influxdb/files/1019301/nmon2influxdb.zip)

**Comment by rodypr06** [comment]
Hi Alain,

I tried the new version and got the same error, "panic: runtime error: index out of range". I have attached the debug file.

Thanks again for your help!

[nmon2influxdb.txt](https://github.com/adejoux/nmon2influxdb/files/1019423/nmon2influxdb.txt)

**Comment by adejoux** [comment]
Hello,

Sorry it's hard to test without the exact same HMC version. Here a new version. Not sure if it will solved the issue. No need to give me the debug file. Just the first output you gave me with the panic section should be enough.

It will give me the line in the code where the error happens.

Thanks,

Alain
[nmon2influxdb.zip](https://github.com/adejoux/nmon2influxdb/files/1019592/nmon2influxdb.zip)

**Comment by rodypr06** [comment]
Hi,

Thanks for the update, I installed the new version, yet same error, here is
the output:

# ./nmon2influxdb hmc import
2017/05/22 15:05:27 Using configuration file /root/.nmon2influxdb.cfg
2017/05/22 15:05:27 Fetching 10 latest samples. 30 seconds interval.
2017/05/22 15:05:27 Getting list of managed systems
2017/05/22 15:05:33 MANAGED SYSTEM SERVER-8202-E4C-SN0636EBT
2017/05/22 15:05:38 managed system metrics:       80 points fetched.
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/adejoux/nmon2influxdb/hmc.Import(0xc42019a000)
    /home/adejoux/devel/go/src/
github.com/adejoux/nmon2influxdb/hmc/import.go:320 +0x40be
github.com/codegangsta/cli.HandleAction(0x809ae0, 0x8cda10, 0xc42019a000,
0xc420066f00, 0x0)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/codegangsta/cli.Command.Run(0x8b656c, 0x6, 0x0, 0x0, 0x0, 0x0,
0x0, 0x8bc043, 0x13, 0x0, ...)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/command.go:207
+0xb72
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4200e8ea0,
0xc4200dfcc0, 0x0, 0x0)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/codegangsta/cli.Command.startApp(0x8b556b, 0x3, 0x0, 0x0, 0x0,
0x0, 0x0, 0x8b963c, 0xd, 0x0, ...)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/command.go:293
+0x8a3
github.com/codegangsta/cli.Command.Run(0x8b556b, 0x3, 0x0, 0x0, 0x0, 0x0,
0x0, 0x8b963c, 0xd, 0x0, ...)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/command.go:93
+0x14c7
github.com/codegangsta/cli.(*App).Run(0xc4200e8b60, 0xc420010150, 0x3, 0x3,
0x0, 0x0)
    /home/adejoux/devel/go/src/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()

Regards,

- Roderick

**Comment by adejoux** [comment]
Hello,

I updated the code to check all values. I hope this version will work for you :). If you can test it.

Thanks,

Alain
[nmon2influxdb.zip](https://github.com/adejoux/nmon2influxdb/files/1021829/nmon2influxdb.zip)

**Comment by rodypr06** [comment]
Amazing! it works!! It imported all the managed systems and its lpars, and
I was able to graph them in Grafana.

Thanks for all the help!

**Comment by adejoux** [comment]
great news :) 

Thanks for your help :)
