### ISSUE TITLE
All points are permanently sent when importing file

### ISSUE THREAD

**Issue by sbengo** [adejoux/nmon2influxdb#55]
Hi!
First of all, thanks for that great tool!

I'm testing nmon2influxdb to get metrics of some devices.
I have set up a simple bash script on cron.d that runs every minute with the following command on 2 different host:
`/opt/nmon2influxdb/nmon2influxdb import <HOST1>:<PATH>/nmon/HOST_YYMMDD_0000.nmon`
`/opt/nmon2influxdb/nmon2influxdb import <HOST2>:<PATH>/nmon/HOST_YYMMDD_0000.nmon`

As I have seen, when the checksum of the file changes (every 1 minute) and aparently all points (older than now and the new ones) on the file are sent permanently. So a question rises up:

- Shouldn't the nmon2influx check only for the new points?

![image](https://user-images.githubusercontent.com/13196237/32483719-7a2a7352-c39d-11e7-8dd5-d3d16536ce3c.png)

Plus info:
- The points are written OK to InfluxDB, with no apparently issues.
- The checksum/timestamp measurements are writteng and aparently read OK to/from InfluxDB.

**Comment by adejoux** [comment]
Hello,

Thanks for submitting this bug. Can you try the version I attached in issue #54 ? 

Regards,

Alain

**Comment by adejoux** [comment]
Hello,

Let me know if you still have the issue.

Regards,

Alain
