### ISSUE TITLE
metastore database error for hmc import

### ISSUE THREAD

**Issue by dsismanis** [adejoux/nmon2influxdb#63]
Hi,

Running nmon2influxdb version 2.1.5.
And InfluxDB version: 1.5.4.

Running my first hmc import using : nmon2influxdb --debug --debug-file nmon2influxdb.debug hmc import.

I see the following :
Creating InfluxDB database nmon2influxdbHMC
Getting list of managed systems
MANAGED SYSTEM ....****
....
... all the metrics...
..
managed system metrics:    10466 points fetched.
{"error":"metastore database error: database not found: nmon2influxdbHMC"}

I'm assuming i don't need to create the influxDB here?
What am i missing?

Regards.

**Comment by adejoux** [comment]
Hello,

I tested with the same version and it created properly the database. Can you check in influxdb if the database nmon2influxdbHMC has been created ?

Regards,

Alain

**Comment by dsismanis** [comment]
Hi,

DB was not created.
I restarted the VM and reran and it worked.
Maybe i needed to restart the influxdb service?
DB is there now. Moving on....

Thanks for looking.

**Comment by adejoux** [comment]
Great news. Not sure what it was not created on the first time. But great if it's ok now :)
