### ISSUE TITLE
Grafana dashboard plot overlapped

### ISSUE THREAD

**Issue by xocoru** [adejoux/nmon2influxdb#67]
take a look:

![image](https://user-images.githubusercontent.com/2736070/50140849-110f5900-02b7-11e9-82a9-4ed9bdac3fc4.png)

**Comment by xocoru** [comment]
is it possible to generate kind of simple dashboards ? without includes, just one by one ?

**Comment by adejoux** [comment]
Hello,

Did you use the dashboard from grafana.com ? Here the link https://grafana.com/dashboards/1555

You should not have errors with it. 

I am not sure what you means by "without includes". Are you talking about the defautl template ?


Regards,

Alain

**Comment by xocoru** [comment]
@adejoux no this is autogenerated dashboard.
```
$ ./nmon2influxdb import -f -b /mnt/c/Users/IvanovAA/Desktop/terrance_181217_1811.nmon
2018/12/19 18:48:32 Using configuration file /home/aivanov/.nmon2influxdb.cfg
2018/12/19 18:48:33 NMON file separator: ,
##############################################################################################################################
File /mnt/c/Users/IvanovAA/Desktop/terrance_181217_1811.nmon imported : 633600 points !
2018/12/19 18:48:50 Dashboard uploaded to grafana
```

'without includes' i mean no ROW (grafana panel element) cause looks like there is a problem.

**Comment by adejoux** [comment]
Ok.

If possible you should us the dashboards from grafana.com. It's a lot better now. 

This function to build dashboard was from before it was possible to share dashboard easily.

I improved the dashboards on grafana.com by a lot. They have more informations.

Maybe I should remove completely the feature of autogenerating dashboards.


Regards,

Alain

**Comment by xocoru** [comment]
@adejoux thanks, i tried, but looks like dashboard from grafana.com - for AIX instead of Linux (in my case). 

I will try adopt AIX dashboard to my Linux env.
