### ISSUE TITLE
HMC import

### ISSUE THREAD

**Issue by niar68** [adejoux/nmon2influxdb#68]
Hi, I'm new on this.
Is there any reason why it's not possible to get Assigned Procs to LPAR value?
What I can see so can you get it for Memory.

b reg Niklas

**Comment by adejoux** [comment]
Hello,

Not sure what you means, for me you have it : 
![image](https://user-images.githubusercontent.com/741174/53554176-78f7e080-3b3f-11e9-85e6-22c1889e1823.png)

Regards,

Alain

**Comment by adejoux** [comment]
No feedbacks. Closing issue
