### ISSUE TITLE
HMC import only last 2 hours

### ISSUE THREAD

**Issue by julfur** [adejoux/nmon2influxdb#70]
Hi,

I've started using the HMC import option of nmon2influxdb 2.1.5 and I have troubles importing more than 2 hours of datapoints (which I think is the default time range).

Here's an example :
```
Using configuration file C:\Users\...
Creating InfluxDB database nmon2influxdbHMC
Fetching 20000 latest samples. 30 seconds interval.
Getting list of managed systems
MANAGED SYSTEM 1
managed system metrics:    16969 points fetched.
MANAGED SYSTEM 2
managed system metrics:    16969 points fetched.
Partition              1:     8126 points fetched.
Partition              2:     8126 points fetched.
Partition              3:     9321 points fetched.
Partition              4:     8126 points fetched.
Partition              5:     8126 points fetched.
Partition              6:     8126 points fetched.
Partition              7:     8126 points fetched.
Partition              8:     8126 points fetched.
```

Looking at influx now 
```
> select * from PartitionMemory order by time limit 1
name: PartitionMemory
time                name              partition      system     value
----                ----              ---------      ------     -----
1551708570000000000 BackedPhysicalMem partition system 5120
```
1551708570 = Monday, March 4, 2019 3:09:30 PM
Which is 2 hours prior to me executing the HMC import with 20000 samples asked.

The script says it's collecting the amount of sample asked but they're not inserted in influxdb.
Is this normal behavior ?

PCM data collection is configured to store 6 month of stats points.
Thanks for your work btw, very nice dashboards with grafana.

**Comment by adejoux** [comment]
Hello,

It's a lack on the documentation. I am using the STM(Short Term Metrics) metrics here. I found them more useful(more details) but the hmc is only keeping the last 2 hours. So you should run the import command every 2 hours at least. 

Personally, i am doing it every 10 minutes. 

Regards,

Alain

**Comment by julfur** [comment]
Thanks for the quick reply.

Yeah I went the same way and it will do nicely.
I guess this issue can be closed.

Thanks again,
Best regards

**Comment by adejoux** [comment]
Thanks :)
