### ISSUE TITLE
Nmon2influxdb on RedHat8 on IBM Power

### ISSUE THREAD

**Issue by niar68** [adejoux/nmon2influxdb#76]
Hi,
Is there someone that running nmon2influxdb on Redhat on Power?
I get 
-bash: ./nmon2influxdb: cannot execute binary file: Exec format error
How do I compile it to work on redhat on IBM power?

**Comment by niar68** [comment]
I'm trying to compile it on Power HW but get following:
nmon2influxdb-2.1.6]# go build
go: finding module for package github.com/adejoux/nmon2influxdb/hmc
go: finding module for package github.com/adejoux/nmon2influxdb/nmon2influxdblib
go: finding module for package github.com/adejoux/nmon2influxdb/nmon
go: finding module for package github.com/codegangsta/cli
go: found github.com/adejoux/nmon2influxdb/hmc in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/adejoux/nmon2influxdb/nmon in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/adejoux/nmon2influxdb/nmon2influxdblib in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/codegangsta/cli in github.com/codegangsta/cli v1.22.4
go: std/adejoux/nmon2influxdb-2.1.6 imports
        github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.4: parsing go.mod:
        module declares its path as: github.com/urfave/cli
                but was required as: github.com/codegangsta/cli

Anyone that can help me understand what the issue can be?

**Comment by adejoux** [comment]
Hello,

I updated the code to have all versions available.

Sorry for the late answer. 

Regards,

Alain
