### ISSUE TITLE
Build with GO

### ISSUE THREAD

**Issue by niar68** [adejoux/nmon2influxdb#78]
I really like this product, but I'm trying to build it on redhat 8 on IBM Power  HW.
Soled a lot of things with different openings. But the latest issue I've bumped into I don't really understand.
I've downloaded latest release and when running go build I get:

nmon2influxdb-2.1.6]# go build
go: finding module for package github.com/adejoux/nmon2influxdb/hmc
go: finding module for package github.com/adejoux/nmon2influxdb/nmon2influxdblib
go: finding module for package github.com/adejoux/nmon2influxdb/nmon
go: finding module for package github.com/codegangsta/cli
go: found github.com/adejoux/nmon2influxdb/hmc in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/adejoux/nmon2influxdb/nmon in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/adejoux/nmon2influxdb/nmon2influxdblib in github.com/adejoux/nmon2influxdb v2.1.6+incompatible
go: found github.com/codegangsta/cli in github.com/codegangsta/cli v1.22.4
go: std/adejoux/nmon2influxdb-2.1.6 imports
github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.4: parsing go.mod:
module declares its path as: github.com/urfave/cli
but was required as: github.com/codegangsta/cli

Anyone that can help me understand what the issue can be and perhaps help me solve it?

**Comment by adejoux** [comment]
Hello, 

I updated the code and added module support. The cli part can needs some adjustments but it should work.

Let me know.

Regards,

Alain

**Comment by niar68** [comment]
Hi,

I tried nmon2influxdb_2.1.8_linux_ppc64le.tar.gz and all is working more or less perfect.
The only thing is that I don't get some data from due to ' Skipping sample. Error in sample collection: Processing did not happen because of error in managed system's LTM collection'.
But that has nothing to do with your package. It's something on the HMC.
Very appreciated to get it.
