### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by maniasso** [adejoux/nmon2influxdb#80]
I have a question about the data collection in HMC, by default the samples in configuration file is 10 and each sample is averaging 30 seconds.
I want to run the nmon2influxdb for collect the data every hour, should I change the number of samples to fit inside a hour?
If every sample is 30 seconds and it collect the last 10 samples, this means it collect only last 5 minutes only?
Thank you.

**Comment by adejoux** [comment]
Hello,

You are correct. The goal is to run it by crontab every 5 minutes by default but you can change it like you see fit.

Regards,

Alain
