### ISSUE TITLE
No help topic for 'xxxx.nmon'

### ISSUE THREAD

**Issue by yesl0107** [adejoux/nmon2influxdb#81]
hi,adejoux:
when I import a nmon result file,it response "No help topic for 'xxxxx.nmon'"  xxxx is my host info.
what version I use is below:
nmon2influxdb_2.1.8_linux_64-bit.tar.gz
the same in influxdb version 1.7.1 or 2.0.

How can i resolve this problem?
Looking forward your reply.
Thanks.

**Comment by yesl0107** [comment]
sorry  it`s my mistake.I missed the import words..

**Comment by adejoux** [comment]
No problem.

Thanks
