### ISSUE TITLE
Suggestion - allow wildcard specification for nmon input files

### ISSUE THREAD

**Issue by rmoff** [adejoux/nmon2influxdb#9]
Great tool!

It'd be useful to be able to process a folder of nmon files, not one at a time.

**Comment by rmoff** [comment]
For now, working around with bash loop: 

```
for i in /u01/nmon_output/*.nmon; do /opt/nmon2influxdb-linux-amd64 --server localhost --port 8086 --db nmon import $i; done
```

**Comment by adejoux** [comment]
Other people requested the same thing. So let's do it :)

**Comment by adejoux** [comment]
Issue fixed in master
